version: "2"  # Версия формата конфигурационного файла (v2 — для golangci-lint 2.x)

run:
  timeout: 5m
  relative-path-mode: gomod  # Пути к файлам интерпретируются относительно корня go-модуля
  issues-exit-code: 1  # Код выхода = 1, если найдены ошибки (полезно для CI)
  tests: true  # Анализировать также _test.go файлы
  modules-download-mode: readonly  # Не разрешать загрузку зависимостей во время анализа (безопасно и быстрее на CI)

output: # Настройки вывода результатов линтинга
  formats:
    text: # Формат вывода в терминал
      print-linter-name: true  # Показывать имя линтера рядом с каждым сообщением
      print-issued-lines: true  # Показывать строку кода, где найдена проблема
      colors: true  # Использовать цветной вывод (для лучшей читаемости)

issues: # Общие настройки для обработки проблем
  max-issues-per-linter: 0  # Без лимита на количество ошибок от одного линтера
  max-same-issues: 0  # Без лимита на количество одинаковых ошибок
  uniq-by-line: true  # Отображать максимум одну ошибку на строку (избегает спама от разных линтеров по одной строке)

linters: # Список активных и отключённых линтеров
  default: standard  # Использовать стандартный набор линтеров golangci-lint
  enable: # Явно включенные дополнительные линтеры
    - errcheck        # Проверяет, что ошибки не игнорируются
    - staticcheck     # Глубокий статический анализ (includes gosimple, stylecheck)
    - govet           # Встроенный в Go инструмент анализа (ловит потенциальные баги)
    - gocritic        # Набор продвинутых правил для улучшения качества кода
    - revive          # Проверяет стиль кода, оформление, названия
    - unused          # Находит неиспользуемые переменные, типы, функции
    - gosec           # Проверка на уязвимости и небезопасные практики
    - depguard        # Запрещает импорт указанных пакетов (контроль зависимостей)
    - bodyclose       # Проверяет, что закрывается `resp.Body` у HTTP-запросов
    - asciicheck      # Предупреждает о не-ASCII символах в коде
    - cyclop          # Контролирует цикломатическую сложность функций
    - dupl            # Находит дублированные фрагменты кода
    - ineffassign     # Обнаруживает неиспользуемые присваивания
    - unparam         # Находит неиспользуемые параметры функций
    - errorlint       # Рекомендует использовать `errors.Is` / `errors.As` вместо прямых сравнений
    - errname         # Проверяет имена переменных/типов ошибок (должны содержать "Err")
    - forbidigo       # Запрещает определённые вызовы или конструкции по regex-паттернам
    - contextcheck    # Проверяет, что `context.Context` передаётся в методы/функции
    - containedctx    # Предупреждает, если `context.Context` сохраняется в структуре (плохо)
  disable:
    - gocyclo
    - lll

  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - dupl
          - gosec

  settings:

    gosec:
      config:
        global:
          audit: true
          show-ignored: true
        severity: "medium"
        confidence: "medium"
        
    cyclop:
      max-complexity: 20

    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: "Использование устаревшего пакета io/ioutil запрещено (замените вызовы на аналоги из пакетов os/io)"

    revive:
      severity: warning

    forbidigo:
      exclude-godoc-examples: true
      analyze-types: true
      forbid:
        - pattern: '^fmt\.Print.*$'  # Запрет использования fmt.Print*, fmt.Println и т.д.
          msg: "Запрещено напрямую использовать fmt.Print* для логирования (вместо этого используйте структурированный логгер)"
        - pattern: '^time\.Sleep$'  # Запрет использования time.Sleep
          msg: "Запрещено использовать time.Sleep в продакшен-коде (используй таймеры/контекст)"
        - pattern: '^http\.DefaultClient$'  # Запрет использования небезопасного http.DefaultClient
          msg: "Не используй http.DefaultClient (нет таймаутов); создай *http.Client с таймаутами"

formatters:
  enable:
    - gofumpt
    - gci
    - golines
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/korchizhinskiy/rocket-factory)
      no-inline-comments: false
    golines:
      max-len: 120
