openapi: 3.0.3
info:
  title: OrderService API
  version: 1.0.0
  description: API for work with orders
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: orderv1
  clean: true

# tags:
#   - name: Weather
#     description: Операции с данными о погоде — получение и обновление информации
