---
openapi: 3.1.0
info:
  title: OrderService API
  version: 0.1.0
  description: API for work with orders
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: orderv1
  clean: true

paths:
  /orders:
    $ref: "./path/order_create.yaml"
  /orders/{order_uuid}:
    $ref: "./path/order_get.yaml"
  /orders/{order_uuid}/pay:
    $ref: "./path/order_pay.yaml"
  # /orders:
  #   $ref: "./path/order_create.yaml"
tags:
  - name: Order
