---
openapi: 3.1.0
info:
  title: OrderService API
  version: 1.0.0
  description: API for work with orders
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: orderv1
  clean: true

paths:
  /orders:
    $ref: "./path/create_order.yaml"
# tags:
#   - name: Weather
#     description: Операции с данными о погоде — получение и обновление информации
