// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category Enumeration
type PartCategory int32

const (
	PartCategory_PART_CATEGORY_UNSPECIFIED PartCategory = 0
	PartCategory_PART_CATEGORY_ENGINE      PartCategory = 1
	PartCategory_PART_CATEGORY_FUEL        PartCategory = 2
	PartCategory_PART_CATEGORY_PORTHOLE    PartCategory = 3
	PartCategory_PART_CATEGORY_WING        PartCategory = 4
)

// Enum value maps for PartCategory.
var (
	PartCategory_name = map[int32]string{
		0: "PART_CATEGORY_UNSPECIFIED",
		1: "PART_CATEGORY_ENGINE",
		2: "PART_CATEGORY_FUEL",
		3: "PART_CATEGORY_PORTHOLE",
		4: "PART_CATEGORY_WING",
	}
	PartCategory_value = map[string]int32{
		"PART_CATEGORY_UNSPECIFIED": 0,
		"PART_CATEGORY_ENGINE":      1,
		"PART_CATEGORY_FUEL":        2,
		"PART_CATEGORY_PORTHOLE":    3,
		"PART_CATEGORY_WING":        4,
	}
)

func (x PartCategory) Enum() *PartCategory {
	p := new(PartCategory)
	*p = x
	return p
}

func (x PartCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (PartCategory) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x PartCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartCategory.Descriptor instead.
func (PartCategory) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Part Structure
type Part struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Uuid          string                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                   `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int64                     `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Category      PartCategory              `protobuf:"varint,6,opt,name=category,proto3,enum=inventory.v1.PartCategory" json:"category,omitempty"`
	Dimensions    *Dimensions               `protobuf:"bytes,7,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Manufacturer  *Manufacturer             `protobuf:"bytes,8,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Tags          []string                  `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]*MetadataValue `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp    `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp    `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Part) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Part) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Part) GetCategory() PartCategory {
	if x != nil {
		return x.Category
	}
	return PartCategory_PART_CATEGORY_UNSPECIFIED
}

func (x *Part) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Part) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *Part) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Part) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Dimension Structure
type Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float64                `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Dimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Dimensions) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Dimension Structure
type Manufacturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

// Metadata Value Structure
type MetadataValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*MetadataValue_StringValue
	//	*MetadataValue_Int64Value
	//	*MetadataValue_DoubleValue
	//	*MetadataValue_BoolValue
	Type          isMetadataValue_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataValue) GetType() isMetadataValue_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MetadataValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Type.(*MetadataValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MetadataValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Type.(*MetadataValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *MetadataValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Type.(*MetadataValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MetadataValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Type.(*MetadataValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isMetadataValue_Type interface {
	isMetadataValue_Type()
}

type MetadataValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MetadataValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type MetadataValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MetadataValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*MetadataValue_StringValue) isMetadataValue_Type() {}

func (*MetadataValue_Int64Value) isMetadataValue_Type() {}

func (*MetadataValue_DoubleValue) isMetadataValue_Type() {}

func (*MetadataValue_BoolValue) isMetadataValue_Type() {}

// Filters for List of Parts
type PartsFilter struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuids                 []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Names                 []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Categories            []PartCategory         `protobuf:"varint,3,rep,packed,name=categories,proto3,enum=inventory.v1.PartCategory" json:"categories,omitempty"`
	ManufactorerCountries []string               `protobuf:"bytes,4,rep,name=manufactorer_countries,json=manufactorerCountries,proto3" json:"manufactorer_countries,omitempty"`
	Tags                  []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PartsFilter) Reset() {
	*x = PartsFilter{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsFilter) ProtoMessage() {}

func (x *PartsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsFilter.ProtoReflect.Descriptor instead.
func (*PartsFilter) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *PartsFilter) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PartsFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PartsFilter) GetCategories() []PartCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PartsFilter) GetManufactorerCountries() []string {
	if x != nil {
		return x.ManufactorerCountries
	}
	return nil
}

func (x *PartsFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request data for get List of Parts
type ListPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PartsFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartRequest) Reset() {
	*x = ListPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartRequest) ProtoMessage() {}

func (x *ListPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartRequest.ProtoReflect.Descriptor instead.
func (*ListPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ListPartRequest) GetFilter() *PartsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response data with List of Parts
type ListPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*Part                `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartResponse) Reset() {
	*x = ListPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartResponse) ProtoMessage() {}

func (x *ListPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartResponse.ProtoReflect.Descriptor instead.
func (*ListPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListPartResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x05\n" +
	"\x04Part\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12(\n" +
	"\vdescription\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdescription\x12\x1c\n" +
	"\x05price\x18\x04 \x01(\x01B\x06\xbaH\x03\xc8\x01\x01R\x05price\x12-\n" +
	"\x0estock_quantity\x18\x05 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\rstockQuantity\x12>\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x1a.inventory.v1.PartCategoryB\x06\xbaH\x03\xc8\x01\x01R\bcategory\x12@\n" +
	"\n" +
	"dimensions\x18\a \x01(\v2\x18.inventory.v1.DimensionsB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"dimensions\x12F\n" +
	"\fmanufacturer\x18\b \x01(\v2\x1a.inventory.v1.ManufacturerB\x06\xbaH\x03\xc8\x01\x01R\fmanufacturer\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12<\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2 .inventory.v1.Part.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aX\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.inventory.v1.MetadataValueR\x05value:\x028\x01\"\x8a\x01\n" +
	"\n" +
	"Dimensions\x12\x1e\n" +
	"\x06length\x18\x01 \x01(\x01B\x06\xbaH\x03\xc8\x01\x01R\x06length\x12\x1c\n" +
	"\x05width\x18\x02 \x01(\x01B\x06\xbaH\x03\xc8\x01\x01R\x05width\x12\x1e\n" +
	"\x06height\x18\x03 \x01(\x01B\x06\xbaH\x03\xc8\x01\x01R\x06height\x12\x1e\n" +
	"\x06weight\x18\x04 \x01(\x01B\x06\xbaH\x03\xc8\x01\x01R\x06weight\"n\n" +
	"\fManufacturer\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\acountry\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\acountry\x12 \n" +
	"\awebsite\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\awebsite\"\xa5\x01\n" +
	"\rMetadataValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\x06\n" +
	"\x04type\"\xcf\x01\n" +
	"\vPartsFilter\x12#\n" +
	"\x05uuids\x18\x01 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\x05uuids\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12:\n" +
	"\n" +
	"categories\x18\x03 \x03(\x0e2\x1a.inventory.v1.PartCategoryR\n" +
	"categories\x125\n" +
	"\x16manufactorer_countries\x18\x04 \x03(\tR\x15manufactorerCountries\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"D\n" +
	"\x0fListPartRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.inventory.v1.PartsFilterR\x06filter\"<\n" +
	"\x10ListPartResponse\x12(\n" +
	"\x05parts\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x05parts*\x93\x01\n" +
	"\fPartCategory\x12\x1d\n" +
	"\x19PART_CATEGORY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PART_CATEGORY_ENGINE\x10\x01\x12\x16\n" +
	"\x12PART_CATEGORY_FUEL\x10\x02\x12\x1a\n" +
	"\x16PART_CATEGORY_PORTHOLE\x10\x03\x12\x16\n" +
	"\x12PART_CATEGORY_WING\x10\x042]\n" +
	"\x10InventoryService\x12I\n" +
	"\bListPart\x12\x1d.inventory.v1.ListPartRequest\x1a\x1e.inventory.v1.ListPartResponseB\xc7\x01\n" +
	"\x10com.inventory.v1B\x0eInventoryProtoP\x01ZRgithub.com/korchizhinskiy/rocket-factory/shared/pkg/proto/inventory/v1;inventoryv1\xa2\x02\x03IXX\xaa\x02\fInventory.V1\xca\x02\fInventory\\V1\xe2\x02\x18Inventory\\V1\\GPBMetadata\xea\x02\rInventory::V1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var (
	file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_inventory_v1_inventory_proto_msgTypes  = make([]protoimpl.MessageInfo, 8)
	file_inventory_v1_inventory_proto_goTypes   = []any{
		(PartCategory)(0),             // 0: inventory.v1.PartCategory
		(*Part)(nil),                  // 1: inventory.v1.Part
		(*Dimensions)(nil),            // 2: inventory.v1.Dimensions
		(*Manufacturer)(nil),          // 3: inventory.v1.Manufacturer
		(*MetadataValue)(nil),         // 4: inventory.v1.MetadataValue
		(*PartsFilter)(nil),           // 5: inventory.v1.PartsFilter
		(*ListPartRequest)(nil),       // 6: inventory.v1.ListPartRequest
		(*ListPartResponse)(nil),      // 7: inventory.v1.ListPartResponse
		nil,                           // 8: inventory.v1.Part.MetadataEntry
		(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	}
)

var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.Part.category:type_name -> inventory.v1.PartCategory
	2,  // 1: inventory.v1.Part.dimensions:type_name -> inventory.v1.Dimensions
	3,  // 2: inventory.v1.Part.manufacturer:type_name -> inventory.v1.Manufacturer
	8,  // 3: inventory.v1.Part.metadata:type_name -> inventory.v1.Part.MetadataEntry
	9,  // 4: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: inventory.v1.Part.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: inventory.v1.PartsFilter.categories:type_name -> inventory.v1.PartCategory
	5,  // 7: inventory.v1.ListPartRequest.filter:type_name -> inventory.v1.PartsFilter
	1,  // 8: inventory.v1.ListPartResponse.parts:type_name -> inventory.v1.Part
	4,  // 9: inventory.v1.Part.MetadataEntry.value:type_name -> inventory.v1.MetadataValue
	6,  // 10: inventory.v1.InventoryService.ListPart:input_type -> inventory.v1.ListPartRequest
	7,  // 11: inventory.v1.InventoryService.ListPart:output_type -> inventory.v1.ListPartResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	file_inventory_v1_inventory_proto_msgTypes[3].OneofWrappers = []any{
		(*MetadataValue_StringValue)(nil),
		(*MetadataValue_Int64Value)(nil),
		(*MetadataValue_DoubleValue)(nil),
		(*MetadataValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
