// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetOrderByIdParams is parameters of GetOrderById operation.
type GetOrderByIdParams struct {
	OrderUUID uuid.UUID
}

func unpackGetOrderByIdParams(packed middleware.Parameters) (params GetOrderByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderUUID",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetOrderByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderByIdParams, _ error) {
	// Decode path: orderUUID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderUUID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderUUID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrdersOrderUUIDCancelPostParams is parameters of POST /orders/{orderUUID}/cancel operation.
type OrdersOrderUUIDCancelPostParams struct {
	OrderUUID uuid.UUID
}

func unpackOrdersOrderUUIDCancelPostParams(packed middleware.Parameters) (params OrdersOrderUUIDCancelPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderUUID",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrdersOrderUUIDCancelPostParams(args [1]string, argsEscaped bool, r *http.Request) (params OrdersOrderUUIDCancelPostParams, _ error) {
	// Decode path: orderUUID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderUUID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderUUID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrdersOrderUUIDPayPostParams is parameters of POST /orders/{orderUUID}/pay operation.
type OrdersOrderUUIDPayPostParams struct {
	OrderUUID uuid.UUID
}

func unpackOrdersOrderUUIDPayPostParams(packed middleware.Parameters) (params OrdersOrderUUIDPayPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderUUID",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrdersOrderUUIDPayPostParams(args [1]string, argsEscaped bool, r *http.Request) (params OrdersOrderUUIDPayPostParams, _ error) {
	// Decode path: orderUUID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderUUID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderUUID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
