// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Cancel order.
	//
	// POST /api/v1/orders/{orderUUID}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Создание заказа.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *OrderCreateRequest) (CreateOrderRes, error)
	// GetOrderByID implements GetOrderByID operation.
	//
	// Получение заказа по идентификатору.
	//
	// GET /api/v1/orders/{orderUUID}
	GetOrderByID(ctx context.Context, params GetOrderByIDParams) (GetOrderByIDRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Оплата заказа.
	//
	// POST /api/v1/orders/{orderUUID}/pay
	PayOrder(ctx context.Context, req *OrderPayRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
