// Code generated by ogen, DO NOT EDIT.

package orderv1

// OperationName is the ogen operation name
type OperationName = string

const (
	GetOrderByIdOperation              OperationName = "GetOrderById"
	OrdersOrderUUIDCancelPostOperation OperationName = "OrdersOrderUUIDCancelPost"
	OrdersOrderUUIDPayPostOperation    OperationName = "OrdersOrderUUIDPayPost"
	OrdersPostOperation                OperationName = "OrdersPost"
)
