// Code generated by ogen, DO NOT EDIT.
package orderv1

type APIV1OrdersOrderUUIDCancelPostRes interface {
	aPIV1OrdersOrderUUIDCancelPostRes()
}

type APIV1OrdersOrderUUIDPayPostRes interface {
	aPIV1OrdersOrderUUIDPayPostRes()
}

type APIV1OrdersPostRes interface {
	aPIV1OrdersPostRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}
