// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1OrdersOrderUUIDCancelPost implements POST /api/v1/orders/{orderUUID}/cancel operation.
	//
	// Cancel order.
	//
	// POST /api/v1/orders/{orderUUID}/cancel
	APIV1OrdersOrderUUIDCancelPost(ctx context.Context, params APIV1OrdersOrderUUIDCancelPostParams) (APIV1OrdersOrderUUIDCancelPostRes, error)
	// APIV1OrdersOrderUUIDPayPost implements POST /api/v1/orders/{orderUUID}/pay operation.
	//
	// Оплата заказа.
	//
	// POST /api/v1/orders/{orderUUID}/pay
	APIV1OrdersOrderUUIDPayPost(ctx context.Context, req *OrderPayRequest, params APIV1OrdersOrderUUIDPayPostParams) (APIV1OrdersOrderUUIDPayPostRes, error)
	// APIV1OrdersPost implements POST /api/v1/orders operation.
	//
	// Создание заказа.
	//
	// POST /api/v1/orders
	APIV1OrdersPost(ctx context.Context, req *OrderCreateRequest) (APIV1OrdersPostRes, error)
	// GetOrderById implements GetOrderById operation.
	//
	// Получение заказа по идентификатору.
	//
	// GET /api/v1/orders/{orderUUID}
	GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
