// Code generated by ogen, DO NOT EDIT.

package orderv1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation  OperationName = "CancelOrder"
	CreateOrderOperation  OperationName = "CreateOrder"
	GetOrderByIDOperation OperationName = "GetOrderByID"
	PayOrderOperation     OperationName = "PayOrder"
)
