// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1OrdersOrderUUIDCancelPost implements POST /api/v1/orders/{orderUUID}/cancel operation.
//
// Cancel order.
//
// POST /api/v1/orders/{orderUUID}/cancel
func (UnimplementedHandler) APIV1OrdersOrderUUIDCancelPost(ctx context.Context, params APIV1OrdersOrderUUIDCancelPostParams) (r APIV1OrdersOrderUUIDCancelPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersOrderUUIDPayPost implements POST /api/v1/orders/{orderUUID}/pay operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{orderUUID}/pay
func (UnimplementedHandler) APIV1OrdersOrderUUIDPayPost(ctx context.Context, req *OrderPayRequest, params APIV1OrdersOrderUUIDPayPostParams) (r APIV1OrdersOrderUUIDPayPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersPost implements POST /api/v1/orders operation.
//
// Создание заказа.
//
// POST /api/v1/orders
func (UnimplementedHandler) APIV1OrdersPost(ctx context.Context, req *OrderCreateRequest) (r APIV1OrdersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderById implements GetOrderById operation.
//
// Получение заказа по идентификатору.
//
// GET /api/v1/orders/{orderUUID}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
