// Code generated by ogen, DO NOT EDIT.
package orderv1

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type OrdersOrderUUIDCancelPostRes interface {
	ordersOrderUUIDCancelPostRes()
}

type OrdersOrderUUIDPayPostRes interface {
	ordersOrderUUIDPayPostRes()
}

type OrdersPostRes interface {
	ordersPostRes()
}
