// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetOrderById implements GetOrderById operation.
//
// Получение заказа по идентификатору.
//
// GET /orders/{orderUUID}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersOrderUUIDCancelPost implements POST /orders/{orderUUID}/cancel operation.
//
// Cancel order.
//
// POST /orders/{orderUUID}/cancel
func (UnimplementedHandler) OrdersOrderUUIDCancelPost(ctx context.Context, params OrdersOrderUUIDCancelPostParams) (r OrdersOrderUUIDCancelPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersOrderUUIDPayPost implements POST /orders/{orderUUID}/pay operation.
//
// Создание заказа.
//
// POST /orders/{orderUUID}/pay
func (UnimplementedHandler) OrdersOrderUUIDPayPost(ctx context.Context, req *OrderPayRequest, params OrdersOrderUUIDPayPostParams) (r OrdersOrderUUIDPayPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersPost implements POST /orders operation.
//
// Создание заказа.
//
// POST /orders
func (UnimplementedHandler) OrdersPost(ctx context.Context, req *OrderCreateRequest) (r OrdersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericStatusCode) {
	r = new(GenericStatusCode)
	return r
}
