// Code generated by ogen, DO NOT EDIT.

package orderv1

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1OrdersOrderUUIDCancelPostOperation OperationName = "APIV1OrdersOrderUUIDCancelPost"
	APIV1OrdersOrderUUIDPayPostOperation    OperationName = "APIV1OrdersOrderUUIDPayPost"
	APIV1OrdersPostOperation                OperationName = "APIV1OrdersPost"
	GetOrderByIdOperation                   OperationName = "GetOrderById"
)
